// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xavjrajtpjlyeobtxiuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhdmpyYWp0cGpseWVvYnR4aXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTcyMTYsImV4cCI6MjA2NzU5MzIxNn0.w6_znMNfh6oX8ZO4Drw48eExbhSsbChCatls0E42kZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});